### PR TITLE
Update lfw_fuel to use latest Keras and Python 3

### PR DESCRIPTION
**Pull request by charlesreid1**
This commit mainly affects the `lfw_fuel` example CNN. It brings the neural network up to date with the latest Keras API, and updates two lines to play nice with both Python 2 and Python 3.

Note that the call to `np.asarray(list(map(cropImage, X)))` is comparable in speed to uglier multi-line alternatives (like pre-allocating an empty array and populating it one element at a time). See [this gist](https://gist.github.com/charlesreid1/436c51eae1e6a0d011d86f3796dec853) for a timing comparison. 

[This SO thread](http://stackoverflow.com/questions/367565/how-do-i-build-a-numpy-array-from-a-generator#580416) is also interesting. It mentions `np.fromiter()`, which unfortunately only works for 1D arrays.

### CODE REVIEW

**Comment by charlesreid1** [comment]
This PR had a few issues crop up when tested outside of my regular environment. Will send an improved pull request that's tested with both Python 2 and Python 3 shortly.

**Comment by charlesreid1** [comment]
Just needed a `pip2 install --upgrade keras`

Also, using fuel from Python 2 necessitated adding the following line to `~/.fuelrc`:

```
floatX : "float32"
```

**Comment by charlesreid1** [comment]
Also relevant: [gist](https://gist.github.com/charlesreid1/5d764ad9e3942197dd89ffa8e49ea6f5) with output from Python 2 and Python 3 running updated `run-lfw.py` script.

**Comment by charlesreid1** [comment]
Adding a few more fixes to core `lfw_fuel.py` functionality. These allow users to use Python 2 or Python 3 to download/convert the dataset using the `fuel-{download,convert}` steps specified in the README. These changes have been tested and are successful with both Python 2 and Python 3.

This pull request got a bit complicated as I kept working on it, so please take your time going through it and let me know if you have questions.

Also, thanks for putting together some really great tools! Going through this code has been a great learning experience. :-)

**Comment by dribnet** [comment]
hi - sorry for the dreadful delay. This library is poorly maintained since Fuel is downstream from Theano - which itself has been deprecated as a dependency since it is being retired.

In any case I'm merging this in. Thanks for your contribution.

**Pull request merged**
